[global]
keyboard = "es"
country = "cl"
fqdn = "Proxmox.local"
mailto = "e@gm.com"
timezone = "America/Santiago"
root_password = "Pve@2025!!"

[network]
source = "from-answer"
cidr = "192.168.1.134/24"
gateway = "192.168.1.1"
dns = "1.1.1.1"

[network.filter]
type = "nic0"

[disk-setup]
filesystem = "ext4"
disk_list = ["nvme0n1"]
lvm.maxroot = 60
lvm.swapsize = 2
